// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/CenteredColumn.tsx": () => import("../components/mockups/hero-variants/CenteredColumn.tsx"),
  "./components/mockups/hero-variants/ProfileLed.tsx": () => import("../components/mockups/hero-variants/ProfileLed.tsx"),
  "./components/mockups/hero-variants/TerminalFirst.tsx": () => import("../components/mockups/hero-variants/TerminalFirst.tsx")
};
